const images: any = {
  'a8-1': require('./a8-1.jpg'),
  'a8-2': require('./a8-2.jpg'),
  'b3-1': require('./b3-1.jpg'),
  'b3-2': require('./b3-2.jpg'),
  'b3-3': require('./b3-3.jpg'),
  'g1-1': require('./g1-1.jpg'),
  'g2-1': require('./g2-1.jpg'),
  'g3-1': require('./g3-1.jpg'),
  'g3-2': require('./g3-2.jpg'),
  'g3-3': require('./g3-3.jpg'),
  'g3-4': require('./g3-4.jpg'),
  'g8-1': require('./g8-1.jpg'),
  'g8-2': require('./g8-2.jpg'),
  'gang8-1-1': require('./gang8-1-1.jpg'),
  'ganthuvien2-1': require('./ganthuvien2-1.jpg'),
  'hoitruong2-1': require('./hoitruong2-1.jpg'),
  'k4-1': require('./k4-1.jpg'),
  'k6-1': require('./k6-1.jpg'),
  'k6-2': require('./k6-2.jpg'),
  'khutuhoc1-1': require('./khutuhoc1-1.jpg'),
  'khutuhoc1-2': require('./khutuhoc1-2.jpg'),
  'nhahanhchinh-1': require('./nhahanhchinh-1.jpg'),
  'nhatruyenthong-1': require('./nhatruyenthong-1.jpg'),
  'nhatruyenthong-2': require('./nhatruyenthong-2.jpg'),
  'nhaxe-2-1': require('./nhaxe-2-1.jpg'),
  'nhaxe-2-2': require('./nhaxe-2-2.jpg'),
  'sanco-1': require('./sanco-1.jpg'),
  'sanco-2': require('./sanco-2.jpg'),
  'sauhoitruong2-1': require('./sauhoitruong2-1.jpg'),
  'sauhoitruong2-2': require('./sauhoitruong2-2.jpg'),
  'sauhoitruong2-3': require('./sauhoitruong2-3.jpg'),
  'stadium2-1': require('./stadium2-1.jpg'),
  'thuvien-1': require('./thuvien-1.jpg'),
  'thuvien-2': require('./thuvien-2.jpg'),
  'trainhathidau2-1-1': require('./trainhathidau2-1-1.jpg'),
  'xuong1-1': require('./xuong1-1.jpg'),
  'xuong1-2': require('./xuong1-2.jpg'),
  'xuong2-1': require('./xuong2-1.jpg')
}

export const getImage = (src: string) => images[src]